# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ffc87cf01691739ea67599be169cbbda2729c86a8c86db5ecbfdb14238f0098295864eabfbfb9b6bf21ce50c176512651637c10c859a6e95da7c737399a540d1

test:
  secret_key_base: 078d285b93a0a9c4332dbc1331df3a22e5acb7d0b3e2d580e7a0e6115e5e24aef43f9632ecbd0550da0d022a5c4e14cc4cce0d6675d231aa07cd4da2d597af0e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
